### ISSUE TITLE
last_g_zero=True sometimes gives an error 

### ISSUE THREAD

**Issue by lukas-stelzl** [bio-phys/PyDHAMed#2]
```python
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-36-882a6db4a90e> in <module>()
----> 1 og = run_dhamed(c_l, -np.log(v_ar), g_init=og, numerical_gradients=False, last_g_zero=True)

/Users/lukas/Projects/DHAMed/public-dhamed/PyDHAMed/pydhamed/optimize_dhamed.pyc in grad_dhamed_likelihood_ref_0(g_prime, g, ip, jp, ti, tj, vi, vj, nk, nijp)
     88     grad = np.zeros(g.shape[0] )
     89     grad[:-1]  += nk[:-1]
---> 90     grad = loop_grad_dhamed_likelihood_0(grad,g, ip, jp, ti, tj, vi, vj, nijp)
     91     return grad[:-1]
     92 

ZeroDivisionError: division by zero
```

**Comment by lscalfi** [comment]
Hi,

I have been trying to use your code (with python2.7) and I think I have the same issue:
```python
Traceback (most recent call last):
  File "dhamed.py", line 28, in <module>
    og = pyd.run_dhamed(count_list, -log(bias_ar))
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py", line 170, in run_dhamed
    og = min_dhamed_bfgs(g_init, ip, jp, ti, tj, vi, vj, n_out, nijp, **kwargs)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py", line 199, in min_dhamed_bfgs
    fprime=grad_dhamed_likelihood_ref_0, **kwargs)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 859, in fmin_bfgs
    res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 934, in _minimize_bfgs
    old_fval, old_old_fval, amin=1e-100, amax=1e100)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 765, in _line_search_wolfe12
    **kwargs)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/linesearch.py", line 101, in line_search_wolfe1
    c1=c1, c2=c2, amax=amax, amin=amin, xtol=xtol)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/linesearch.py", line 175, in scalar_search_wolfe1
    derphi1 = derphi(stp)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/linesearch.py", line 90, in derphi
    gval[0] = fprime(xk + s*pk, *newargs)
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py", line 90, in grad_dhamed_likelihood_ref_0
    grad = loop_grad_dhamed_likelihood_0(grad,g, ip, jp, ti, tj, vi, vj, nijp)
ZeroDivisionError: division by zero
```

Also, if I specify:
`og = pyd.run_dhamed(count_list, -log(bias_ar), last_g_zero=False)`
the code runs giving the following warnings:
```python 
5493
loglike-start 147348571.403
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py:72: RuntimeWarning: divide by zero encountered in double_scalars
  grad[j] += -nijp[ipair] / (1.0 + ti[ipair]/(vij*tj[ipair]))
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py:72: RuntimeWarning: overflow encountered in double_scalars
  grad[j] += -nijp[ipair] / (1.0 + ti[ipair]/(vij*tj[ipair]))
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py:67: RuntimeWarning: overflow encountered in exp
  vij = np.exp(vj[ipair]-g[j]-vi[ipair]+g[i])
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/PyDHAMed-0.1-py2.7.egg/pydhamed/optimize_dhamed.py:70: RuntimeWarning: overflow encountered in double_scalars
  grad[i] += -nijp[ipair] / (1.0 + tj[ipair]*vij/ti[ipair])
Warning: Desired error not necessarily achieved due to precision loss.
         Current function value: -79892950.313293
         Iterations: 1
         Function evaluations: 26
         Gradient evaluations: 23
time elapsed 1.19636082649 s
```
And the array in the output doesn't look as a PMF. Could you tell me what last_g_zero is for? 
Hope this helps,

Laura

**Comment by lukas-stelzl** [comment]
Hi Laura,
Thanks so much for your comment, that's very helpful! 

"last_g_zero" sets the the log-weight of the last state to zero. This we can do, as we are only interested in the relative free energies. Doing so restricts the space for the solution and should help. One thing, that I should probably change is that the output array has to be multiplied by minus one to be a PMF. 

I'm travelling until Tuesday, but I'm very keen to get to the bottom of this once I'm back!

**Comment by lukas-stelzl** [comment]
Hi Laura,
I have added a new default option "jit_gradient=False" to the run_dhamed() function. This option switches own off the use of Numba to speed up the calculation of the gradients for the optimisation of the DHAMed effective log-likelihood. With this new default setting, the calculation now runs flawlessly on both my Macbook and on my Linux workstation. 

For most DHAMed calculations I have run, the speed up in the gradient calculation provided by Numba (by setting "jit_gradient=True") was not required. The original problem must be have something to do with the way I am using Numba in the gradient calculation. I'm investigating this further.

In the meanwhile could you try to 

git clone https://github.com/bio-phys/PyDHAMed.git
cd PyDHAMed
pip install . 

and run your calculation again? I'd hope that the error message disappears. Your feedback would be extremely useful!

You have also mentioned that your PMF looked weird. Is there a minimal example you could provide? I'd be keen to understand why the calculation gives unexpected results:).

**Comment by lscalfi** [comment]
Hi,

The code runs now although I am still getting these warnings:

5383
loglike-start 121531126.036
121531126.036
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/pydhamed/optimize_dhamed.py:109: RuntimeWarning: overflow encountered in double_scalars
  grad[j] += -nijp[ipair] / (1.0 + ti[ipair]/(vij*tj[ipair]))
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/pydhamed/optimize_dhamed.py:109: RuntimeWarning: divide by zero encountered in double_scalars
  grad[j] += -nijp[ipair] / (1.0 + ti[ipair]/(vij*tj[ipair]))
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/pydhamed/optimize_dhamed.py:104: RuntimeWarning: overflow encountered in exp
  vij = np.exp(vj[ipair]-g[j]-vi[ipair]+g[i])
/Users/lscalfi/anaconda2/lib/python2.7/site-packages/pydhamed/optimize_dhamed.py:107: RuntimeWarning: overflow encountered in double_scalars
  grad[i] += -nijp[ipair] / (1.0 + tj[ipair]*vij/ti[ipair])
Warning: Desired error not necessarily achieved due to precision loss.
         Current function value: -68818591.386624
         Iterations: 1
         Function evaluations: 26
         Gradient evaluations: 20
time elapsed 1.46079587936 s

I guess they could explain why the PMF is not the expected one (that I also compute using WHAM)?

**Comment by lukas-stelzl** [comment]
Hi Laura,
Thanks a lot for the update!  

Without knowing your inputs it is hard to tell why you get a DHAMed result that looks very different from DHAMed. Inputting the bias potentials, is  a place where things have gone wrong for me (and others), when using DHAMed. What units have your bias potentials? I typically convert the bias potentials into units of kT. Do you have a single bias potential u_i^{alpha} for each structural state i for each umbrella window/simulation run alpha? 

Currently, I'm working on two things, that may be potentially helpful for your case. 1) I'm going to upload an example notebook for the calculation of the GLIC channel ion-permeation PMF from the manuscript soon. 2) Secondly, a colleague is working on a (binless) WHAM code, which uses the same input data as pyDHAMed. The comparison of WHAM and DHAMed for data (in the same format) should provide a good check and should help to track down any problems.    

One thing you could try, is to set 'numerical_gradient=True' when calling run_dhamed. This is possible in latest version of the code. If this is gives a different result than the result than with 'numerical_gradient=False', then this would hint at a potential flaw in the gradient calculation. I don't think this is the problem, but this would be a very quick think to try.

**Comment by lscalfi** [comment]
Hi Lukas,

Thank you for your help, I have tried to set 'numerical_gradient=True' and indeed there is no change. My issue was in the parameters I was using (too many bins/states). I now obtain a reasonable curve very similar to my WHAM.

PS: it is not clear (from the example in the notebook and your readme) if one should input the bias or -log of the bias in the run_dhamed function

**Comment by lukas-stelzl** [comment]
Hi Laura,

Glad to hear that! Thanks a lot for the feedback regarding the bias. I'll clarify that point, you're absolutely right, this needs to be explained.

**Comment by lukas-stelzl** [comment]
5a6e1989660d06151fbb346c10bce842eec6b7a8 finally clarifies the conversion of the bias for the coarse grained RNA example. I'll close this issue.
