### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by lukas-stelzl** [bio-phys/PyDHAMed#6]
Use Travis CI to run tests automatically :-)

**Comment by kain88-de** [comment]
you can copy the config from MDBenchmark once it's done

**Comment by kain88-de** [comment]
https://github.com/bio-phys/MDBenchmark/blob/master/.travis.yml

it only tests the install now but it should get you started.

**Comment by lukas-stelzl** [comment]
Thanks a lot!

**Comment by kain88-de** [comment]
if numba is a problem I can help you on monday.

**Comment by lukas-stelzl** [comment]
- [x]  automatic build on Travis works

- [x] nosetests runs (for the single but crucial tests whether I get the correct PMF :-) 

I'll close the issue for now. Thanks @kain88-de  and @mimischi !

**Comment by kain88-de** [comment]
@lukas-stelzl nosetest is not actively maintained anymore. All major python tools (numpy scipy etc) switched to pytest.
